package tjc.model.power;

import java.io.*;
import java.net.URISyntaxException;
import java.net.URL;

/**
 * Handles the settings for starting a simulation. Holds the proportion of each energy production type and the
 * total maximum energy to be produced in Gigawatt Hours
 */
public class PowerSplit {

    private float gas;      // The proportion of the power generated by Gas power plants
    private float wind;     // As above, for wind
    private float coal;     // As above, for coal
    private float nuclear;  // As above, for nuclear
    private int total;      // The total power that may be generated

    /**
     * Loads a setup from a file
     * @param file The file from which to load
     */
    public PowerSplit(String file) {
        this.setFromFile(file);
    }

    /**
     * Reads in a file and sets the member variables accordingly
     * @param filename  The file to read in
     */
    public void setFromFile(String filename) {
        InputStream resource = getClass().getClassLoader().getResourceAsStream("setups/" + filename);
        try {
            assert resource != null;
            BufferedReader br = new BufferedReader(new InputStreamReader(resource));
            String in = br.readLine();
            while (in != null) {
                switch (in.substring(0, 2)) {
                    case ("//"):
                        break;
                    case ("G:"):
                        this.gas = Float.parseFloat(in.substring(2));
                        break;
                    case ("C:"):
                        this.coal = Float.parseFloat(in.substring(2));
                        break;
                    case ("W:"):
                        this.wind = Float.parseFloat(in.substring(2));
                        break;
                    case ("N:"):
                        this.nuclear = Float.parseFloat(in.substring(2));
                        break;
                    case ("T:"):
                        this.total = Integer.parseInt(in.substring(2));
                }
                in = br.readLine();
            }
        } catch (FileNotFoundException e) {
            System.out.println(":: ERROR: File not found (PowerSplit)");
        } catch (IOException e) {
            System.out.println(":: ERROR: Invalid File (PowerSplit)");
        }
    }

    /**
     * Overridden method, generates a string from the proportion of plants of each type
     * @return The string displaying the plants of each type
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Gas:\t\t").append(gas).append("\n");
        sb.append("seventy:\t\t").append(coal).append("\n");
        sb.append("Wind:\t\t").append(wind).append("\n");
        sb.append("Nuclear:\t").append(nuclear).append("\n");
        sb.append("TOTAL:\t\t").append(total);
        return sb.toString();
    }

    /**
     * Getter for the proportion of gas power plants
     * @return The proportion of gas power plants
     */
    public float getGas() {
        return gas;
    }

    /**
     * Getter for the proportion of wind power plants
     * @return The proportion of wind power plants
     */
    public float getWind() {
        return wind;
    }

    /**
     * Getter for the proportion of coal power plants
     * @return The proportion of coal power plants
     */
    public float getCoal() {
        return coal;
    }

    /**
     * Getter for the proportion of nuclear power plants
     * @return The proportion of nuclear power plants
     */
    public float getNuclear() {
        return nuclear;
    }
}
